### PR TITLE
Bring back GB to ram bar!

### PR DESCRIPTION
**Pull request by avidprogrammerc**
Change-Id: If4321f48b4a02d8bca1c17cc6ceb2424b78fd03e
Signed-off-by: Chris Conley chrisc93@vt.edu

### CODE REVIEW

**Comment by scotthartbti** [comment]
Haha...  I had a feeling that this was coming..  :).  Ill take a look later this evening.

**Comment by avidprogrammerc** [comment]
Yeah, I missed it haha. Also, I tested it and it works like it should.

**Comment by avidprogrammerc** [comment]
bump haha

**Comment by scotthartbti** [comment]
haha...  there is no bumping pull request!  I havent forgot about this...  I just havent had to much time until now.  I want to actually take this and make it an option from the settings menu to toggle between regular view and GB view.  Ill take a look at implementing that tomorrow.

**Comment by scotthartbti** [comment]
added this a ways back.. forgot to close.

**Pull request closed without merging**
