### PR TITLE
added and resized stat_sys_download for mdpi devices

### PR DESCRIPTION
**Pull request by 7alvi**

### CODE REVIEW

**Comment by scotthartbti** [comment]
I will take a look at this in a bit.  Thanks.

**Comment by scotthartbti** [comment]
I actually just noticed that this is for the jb42 branch...  Was this on purpose or an accident?  The jb42 branch is not longer being supported and development has ended.  All development has and will continue with the jb43 branch.

**Comment by 7alvi** [comment]
It was on purpose. I wasn't aware that it was no longer in development. Without these re sized pngs it gives process.android.media FC while downloading anything (on mdpi devices, of course).

**Comment by scotthartbti** [comment]
This is the first I've heard of this... The regular pngs are straight from
cm ... .  I haven't done anything with the jb42 branch for about 2 weeks...
Possible something else is causing the issue?  I added these pngs to the
jb43 branch and it produced a ton of image inflater errors while
building... Ill take a peek at the cm end of things.

**Comment by 7alvi** [comment]
Hmm..Doing this actually fixed the issue for me. In frameworks/base/core/res/res/drawable-hdpi, there are around 20 .pngs for stat_sys_download while in drawable-mdpi there are only 6 .pngs for same. 
Strangely, in CM's frameworks/base its the same. There are also 6 pngs in drawable-mdpi. And CM works fine without this 'patch' (?). it just fixed the issue for me. The logcat showed missing drawables. Maybe its not needed for every device, I guess.

**Comment by scotthartbti** [comment]
Strange...  I checked the other reputable builds and they are all the same
as mine and cm.  What device are you on?  Also, how long has this been an
issue?  Has it ever worked without those extra drawables?

**Comment by 7alvi** [comment]
I am on HTC Explorer/Pico. I checked sources of other builds I've compiled. They are the same as yours and CM (like you said). I actually reverted this commit and built again with original. It gave that FC again. Lol. It looks as if its needed for this ROM for my device only. You can ignore this pull. I see that it's not required for other builds for my device only. Strange.

**Comment by scotthartbti** [comment]
expired request.

**Pull request closed without merging**
