### PR TITLE
fix: battery stats always reports awake.

### PR DESCRIPTION
**Pull request by ghost**
-Looks like it was just a small derp.

Change-Id: I470b4453447543ebcf6ea3039336e70d2f0d5d91

This looks like the only change that was needed. ;)

### CODE REVIEW

**Comment by scotthartbti** [comment]
Johnny, you said you diffed against the slim file right?  Did you happen to
look at the history to see if there was any commit that I didn't have?
Wondering what went wrong here.. Don't think I touched that file at all...

**Comment by scotthartbti** [comment]
Can you do me a favor?  Shoot me a message on hangouts/talk -
Scott.hart.bti@gmail.com

**Comment by scotthartbti** [comment]
Looking through the history it looks like this was caused directly from this commit: https://github.com/Meticulus/android_frameworks_base/commit/12c6dc2166cbf285957ad96399db387ff15b9049

**Comment by ghost** [comment]
that looks like it. Did you pull that in from somewhere? I wonder if it's broken there too?

**Comment by scotthartbti** [comment]
Yea i cherry picked that way back... forget where from though.  Guess that teaches me to pick shit without going over it completely

**Comment by ghost** [comment]
when maintaining an entire rom I'm sure it's hard to catch everything lol.

**Comment by scotthartbti** [comment]
Yea....  Especially with 4.4...  seems like everything i add breaks something else... like the commit mentioned above.  lol

**Comment by scotthartbti** [comment]
cherry-picked commit 2d38807eb15e4e657e278637cbe9110fb779ef6b

Thanks for the fix.

**Pull request closed without merging**
